-- 1. Créer la table 'messages'
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    content text not null,
    user_id uuid references auth.users not null,
    channel_id text not null, -- 'general', 'cas-cliniques', 'annonces'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Activer le Temps Réel (Realtime) pour cette table
alter publication supabase_realtime add table messages;

-- 3. Sécurité (RLS)
alter table public.messages enable row level security;

-- Politique de lecture : Tout le monde authentifié peut lire (on filtrera côté client sur la page 'membres' qui est protégée)
-- Ou mieux : Seuls les profils 'membre' peuvent lire. Pour simplifier ici on met authentifié, le 'vigile' JS bloquera l'accès à la page.
create policy "Authenticated users can read messages"
    on public.messages for select
    using ( auth.role() = 'authenticated' );

-- Politique d'écriture : Seuls les utilisateurs connectés peuvent écrire
create policy "Authenticated users can insert messages"
    on public.messages for insert
    with check ( auth.role() = 'authenticated' );

-- 4. Vue pour récupérer les infos utilisateur avec le message (optionnel si on fetch séparément, mais plus propre)
-- Pour l'instant on fera le join côté client ou on récupérera le profil simple.
